In [508]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
import numpy as np

In [509]:
dados = "C:/Users/xavier.thiago/Documents/Projeto_Analise_Dados_Caramelo_Store_SENAC_RJ/data/CARAMELO.csv"
df = pd.read_csv(dados, sep=';', encoding='UTF-8')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID Venda             150000 non-null  int64
 1   Loja                 150000 non-null  str
 2   ID Loja              150000 non-null  int64
 3   Estado Loja          150000 non-null  str
 4   Cidade Loja          150000 non-null  str
 5   Nome Cliente         150000 non-null  str
 6   ID Cliente           150000 non-null  int64
 7   Sexo                 150000 non-null  str
 8   Idade                150000 non-null  int64
 9   Estado Cliente       150000 non-null  str
 10  Cidade Cliente       150000 non-null  str
 11  ID Produto           150000 non-null  int64
 12  Categoria Produto    150000 non-null  str
 13  Marca                150000 non-null  str
 14  Data da Compra       150000 non-null  str
 15  Data da Entrega      150000 non-null  str
 16  Metodo de Pagamento  150000 non-null  str
 17  Produto              150000 non-null  str
 18  Valor de Venda       150000 non-null  str
dtypes: int64(5), str(14)
memory usage: 21.7 MB

In [510]:
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',', '.').astype(float)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID Venda             150000 non-null  int64
 1   Loja                 150000 non-null  str
 2   ID Loja              150000 non-null  int64
 3   Estado Loja          150000 non-null  str
 4   Cidade Loja          150000 non-null  str
 5   Nome Cliente         150000 non-null  str
 6   ID Cliente           150000 non-null  int64
 7   Sexo                 150000 non-null  str
 8   Idade                150000 non-null  int64
 9   Estado Cliente       150000 non-null  str
 10  Cidade Cliente       150000 non-null  str
 11  ID Produto           150000 non-null  int64
 12  Categoria Produto    150000 non-null  str
 13  Marca                150000 non-null  str
 14  Data da Compra       150000 non-null  str
 15  Data da Entrega      150000 non-null  str
 16  Metodo de Pagamento  150000 non-null  str
 17  Produto              150000 non-null  str
 18  Valor de Venda       150000 non-null  float64
dtypes: float64(1), int64(5), str(13)
memory usage: 21.7 MB

In [511]:
array_venda = np.array(df['Valor de Venda'])
q1 = np.percentile(array_venda, 25)
q2 = np.percentile(array_venda, 50)
q3 = np.percentile(array_venda, 75)
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

Primeiro quartil (Q1): 32.88
Segundo quartil (Q2, Mediana): 129.23
Terceiro quartil (Q3): 947.0250000000001

Valor de venda por loja

In [512]:
df_valor_venda_loja = df
df_valor_venda_loja = df_valor_venda_loja.groupby(['Loja'])['Valor de Venda'].sum().reset_index().sort_values(by='Valor de Venda', ascending=False)
df_valor_venda_loja

                               Loja  Valor de Venda
10           Mendonça Machado Ltda.   73,919,670.56
7                             Gomes   39,371,215.05
6                         Fernandes   37,107,099.24
0                           Andrade   36,868,599.90
3                             Cunha   36,133,723.77
12                       Moura - ME   35,509,673.51
11                          Moreira   26,847,044.73
17                            Sousa   18,350,601.22
15              Sampaio Viana Ltda.   18,017,479.95
19                           Vargas   17,769,332.66
1   Aparecida da Conceição e Filhos   17,209,636.57
5                 Cunha Mendes S.A.   16,004,067.45
18                         Teixeira   15,717,865.33
13                            Nunes   15,711,971.31
2                           Barbosa   15,571,997.27
8                           Machado   15,438,498.57
4                  Cunha Gomes - EI   15,287,724.29
16                           Santos   15,090,433.84
14            Ribeiro Sampaio Ltda.   15,053,199.25
9                              Melo   14,618,426.65

In [513]:
array_valor_venda_loja = np.array(df_valor_venda_loja['Valor de Venda'])

q1_valor_venda_loja = np.percentile(array_valor_venda_loja, 25)
q2_valor_venda_loja = np.percentile(array_valor_venda_loja, 50)
q3_valor_venda_loja = np.percentile(array_valor_venda_loja, 75)

media_valor_venda_loja = np.mean(array_valor_venda_loja)
mediana_valor_venda_loja = np.median(array_valor_venda_loja)
distancia_valor_venda_loja = (media_valor_venda_loja - mediana_valor_venda_loja) / mediana_valor_venda_loja

iqr_valor_venda_loja = q3_valor_venda_loja - q1_valor_venda_loja
limite_superior_valor_venda_loja = q3_valor_venda_loja + (1.5 * iqr_valor_venda_loja)
limite_inferior_valor_venda_loja = q1_valor_venda_loja - (1.5 * iqr_valor_venda_loja)

print(f'Primeiro quartil (Q1): {q1_valor_venda_loja}')
print(f'Segundo quartil (Q2, Mediana): {q2_valor_venda_loja}')
print(f'Terceiro quartil (Q3): {q3_valor_venda_loja}')

print(f'O valor da média é {media_valor_venda_loja}')
print(f'O valor da mediana é {mediana_valor_venda_loja}')
print(f'A distância entre média e mediana é de {distancia_valor_venda_loja * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_valor_venda_loja}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_valor_venda_loja}')

Primeiro quartil (Q1): 15538622.594999999
Segundo quartil (Q2, Mediana): 17489484.615000002
Terceiro quartil (Q3): 35665686.075
O valor da média é 24779913.055999998
O valor da mediana é 17489484.615000002
A distância entre média e mediana é de 41.68463852129353
O limite superior para detecção de outliers é 65856281.29500001
O limite inferior para detecção de outliers é -14651972.625000007

In [514]:
outliers_valor_venda_loja_limite_inferior = df_valor_venda_loja.loc[df_valor_venda_loja['Valor de Venda'] <= limite_inferior_valor_venda_loja]
outliers_valor_venda_loja_limite_inferior = outliers_valor_venda_loja_limite_inferior.sort_values(by='Valor de Venda')
outliers_valor_venda_loja_limite_inferior

Empty DataFrame
Columns: [Loja, Valor de Venda]
Index: []

In [515]:
outliers_valor_venda_loja_limite_superior = df_valor_venda_loja.loc[df_valor_venda_loja['Valor de Venda'] >= limite_superior_valor_venda_loja]
outliers_valor_venda_loja_limite_superior = outliers_valor_venda_loja_limite_superior.sort_values(by='Valor de Venda')
outliers_valor_venda_loja_limite_superior

                      Loja  Valor de Venda
10  Mendonça Machado Ltda.   73,919,670.56

Valor de venda por estado

In [516]:
df_valor_venda_estado = df
df_valor_venda_estado = df_valor_venda_estado.groupby(['Estado Loja'])['Valor de Venda'].sum().reset_index().sort_values(by='Valor de Venda', ascending=True)
df_valor_venda_estado

  Estado Loja  Valor de Venda
0          BA   30,622,494.10
1          MG   45,855,604.40
3          RS   62,016,085.46
2          RJ   98,194,095.13
4          SP  258,909,982.03

In [517]:
array_valor_venda_estado = np.array(df_valor_venda_estado['Valor de Venda'])

q1_valor_venda_estado = np.percentile(array_valor_venda_estado, 25)
q2_valor_venda_estado = np.percentile(array_valor_venda_estado, 50)
q3_valor_venda_estado = np.percentile(array_valor_venda_estado, 75)

media_valor_venda_estado = np.mean(array_valor_venda_estado)
mediana_valor_venda_estado = np.median(array_valor_venda_estado)
distancia_valor_venda_estado = (media_valor_venda_estado - mediana_valor_venda_estado) / mediana_valor_venda_estado

iqr_valor_venda_estado = q3_valor_venda_estado - q1_valor_venda_estado
limite_superior_valor_venda_estado = q3_valor_venda_estado + (1.5 * iqr_valor_venda_estado)
limite_inferior_valor_venda_estado = q1_valor_venda_estado - (1.5 * iqr_valor_venda_estado)

print(f'Primeiro quartil (Q1): {q1_valor_venda_estado}')
print(f'Segundo quartil (Q2, Mediana): {q2_valor_venda_estado}')
print(f'Terceiro quartil (Q3): {q3_valor_venda_estado}')

print(f'O valor da média é {media_valor_venda_estado}')
print(f'O valor da mediana é {mediana_valor_venda_estado}')
print(f'A distância entre média e mediana é de {distancia_valor_venda_estado * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_valor_venda_estado}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_valor_venda_estado}')

Primeiro quartil (Q1): 45855604.4
Segundo quartil (Q2, Mediana): 62016085.46
Terceiro quartil (Q3): 98194095.13
O valor da média é 99119652.224
O valor da mediana é 62016085.46
A distância entre média e mediana é de 59.82894032860487
O limite superior para detecção de outliers é 176701831.225
O limite inferior para detecção de outliers é -32652131.695

In [518]:
outliers_valor_venda_estado_limite_inferior = df_valor_venda_estado.loc[df_valor_venda_estado['Valor de Venda'] <= limite_inferior_valor_venda_estado]
outliers_valor_venda_estado_limite_inferior = outliers_valor_venda_estado_limite_inferior.sort_values(by='Valor de Venda')
outliers_valor_venda_estado_limite_inferior

Empty DataFrame
Columns: [Estado Loja, Valor de Venda]
Index: []

In [519]:
outliers_valor_venda_estado_limite_superior = df_valor_venda_estado.loc[df_valor_venda_estado['Valor de Venda'] >= limite_superior_valor_venda_estado]
outliers_valor_venda_estado_limite_superior = outliers_valor_venda_estado_limite_superior.sort_values(by='Valor de Venda')
outliers_valor_venda_estado_limite_superior

  Estado Loja  Valor de Venda
4          SP  258,909,982.03

Valor de venda por produto

In [520]:
df_valor_venda_produto = df
df_valor_venda_produto = df_valor_venda_produto.groupby(['Produto'])['Valor de Venda'].sum().reset_index().sort_values(by='Valor de Venda', ascending=True)
df_valor_venda_produto

                   Produto  Valor de Venda
1   A Culpa é das Estrelas      124,794.37
32       O Código Da Vinci      126,218.56
35      O Senhor dos Anéis      130,492.37
0                     1984      132,745.02
36   Orgulho e Preconceito      134,024.75
34      O Pequeno Príncipe      141,604.62
33                O Hobbit      142,204.47
22            Harry Potter      142,264.26
2   A Revolução dos Bichos      143,589.30
15            Dom Casmurro      155,629.60
19                  Feijão      249,765.27
24                   Leite      262,156.63
3                    Arroz      275,320.17
5                 Biscoito      276,557.21
13               Chocolate      289,566.43
25                Macarrão      295,260.69
45                    Suco      301,901.36
39            Refrigerante      307,208.49
26                Manteiga      308,033.74
7                     Café      326,790.75
28                 Moletom    1,079,064.25
41                Sandália    1,180,391.67
11                Camiseta    1,181,912.36
40                    Saia    1,185,923.53
8              Calça Jeans    1,369,719.09
42                  Shorts    1,379,342.97
10           Camisa Social    1,522,545.80
23                 Jaqueta    1,778,857.14
49                   Tênis    1,886,006.00
50                 Vestido    1,931,835.80
9                     Cama    7,285,904.17
27                    Mesa    7,367,955.77
38                    Rack    7,373,110.94
37                Poltrona    7,444,399.84
17            Escrivaninha    7,993,337.79
4                    Banco    8,033,665.66
21            Guarda-roupa    8,145,919.26
6                  Cadeira    8,173,065.74
18                 Estante    8,244,831.07
44                    Sofá    8,489,967.55
16                   Drone   25,690,253.26
43              Smartwatch   27,830,646.35
46                      TV   28,401,147.89
29                 Monitor   30,621,309.99
14    Console de Videogame   31,663,357.68
47                  Tablet   33,088,129.29
30                   Mouse   33,362,050.01
31                Notebook   34,446,750.39
20          Fone de Ouvido   49,368,227.23
12                 Celular   51,362,657.26
48                 Teclado   52,449,847.31

In [521]:
array_valor_venda_produto = np.array(df_valor_venda_produto['Valor de Venda'])

q1_valor_venda_produto = np.percentile(array_valor_venda_produto, 25)
q2_valor_venda_produto = np.percentile(array_valor_venda_produto, 50)
q3_valor_venda_produto = np.percentile(array_valor_venda_produto, 75)

media_valor_venda_produto = np.mean(array_valor_venda_produto)
mediana_valor_venda_produto = np.median(array_valor_venda_produto)
distancia_valor_venda_produto = (media_valor_venda_produto - mediana_valor_venda_produto) / mediana_valor_venda_produto

iqr_valor_venda_produto = q3_valor_venda_produto - q1_valor_venda_produto
limite_superior_valor_venda_produto = q3_valor_venda_produto + (1.5 * iqr_valor_venda_produto)
limite_inferior_valor_venda_produto = q1_valor_venda_produto - (1.5 * iqr_valor_venda_produto)

print(f'Primeiro quartil (Q1): {q1_valor_venda_produto}')
print(f'Segundo quartil (Q2, Mediana): {q2_valor_venda_produto}')
print(f'Terceiro quartil (Q3): {q3_valor_venda_produto}')

print(f'O valor da média é {media_valor_venda_produto}')
print(f'O valor da mediana é {mediana_valor_venda_produto}')
print(f'A distância entre média e mediana é de {distancia_valor_venda_produto * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_valor_venda_produto}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_valor_venda_produto}')

Primeiro quartil (Q1): 275938.69
Segundo quartil (Q2, Mediana): 1379342.97
Terceiro quartil (Q3): 8208948.405
O valor da média é 9717612.963137254
O valor da mediana é 1379342.97
A distância entre média e mediana é de 604.5102758697683
O limite superior para detecção de outliers é 20108462.9775
O limite inferior para detecção de outliers é -11623575.8825

In [522]:
outliers_valor_venda_produto_limite_inferior = df_valor_venda_produto.loc[df_valor_venda_produto['Valor de Venda'] <= limite_inferior_valor_venda_produto]
outliers_valor_venda_produto_limite_inferior = outliers_valor_venda_produto_limite_inferior.sort_values(by='Valor de Venda')
outliers_valor_venda_produto_limite_inferior

Empty DataFrame
Columns: [Produto, Valor de Venda]
Index: []

In [523]:
outliers_valor_venda_produto_limite_superior = df_valor_venda_produto.loc[df_valor_venda_produto['Valor de Venda'] >= limite_superior_valor_venda_produto]
outliers_valor_venda_produto_limite_superior = outliers_valor_venda_produto_limite_superior.sort_values(by='Valor de Venda', ascending=False)
outliers_valor_venda_produto_limite_superior

                 Produto  Valor de Venda
48               Teclado   52,449,847.31
12               Celular   51,362,657.26
20        Fone de Ouvido   49,368,227.23
31              Notebook   34,446,750.39
30                 Mouse   33,362,050.01
47                Tablet   33,088,129.29
14  Console de Videogame   31,663,357.68
29               Monitor   30,621,309.99
46                    TV   28,401,147.89
43            Smartwatch   27,830,646.35
16                 Drone   25,690,253.26

Valor de venda por categoria

In [524]:
df_valor_venda_categoria = df
df_valor_venda_categoria = df_valor_venda_categoria.groupby(['Categoria Produto'])['Valor de Venda'].sum().reset_index().sort_values(by='Valor de Venda', ascending=True)
df_valor_venda_categoria

  Categoria Produto  Valor de Venda
2            Livros    1,373,567.32
0         Alimentos    2,892,560.74
4            Roupas   14,495,598.61
3            Móveis   78,552,157.79
1       Eletrônicos  398,284,376.66

In [525]:
array_valor_venda_categoria = np.array(df_valor_venda_categoria['Valor de Venda'])

q1_valor_venda_categoria = np.percentile(array_valor_venda_categoria, 25)
q2_valor_venda_categoria = np.percentile(array_valor_venda_categoria, 50)
q3_valor_venda_categoria = np.percentile(array_valor_venda_categoria, 75)

media_valor_venda_categoria = np.mean(array_valor_venda_categoria)
mediana_valor_venda_categoria = np.median(array_valor_venda_categoria)
distancia_valor_venda_categoria = (media_valor_venda_categoria - mediana_valor_venda_categoria) / mediana_valor_venda_categoria

iqr_valor_venda_categoria = q3_valor_venda_categoria - q1_valor_venda_categoria
limite_superior_valor_venda_categoria = q3_valor_venda_categoria + (1.5 * iqr_valor_venda_categoria)
limite_inferior_valor_venda_categoria = q1_valor_venda_categoria - (1.5 * iqr_valor_venda_categoria)

print(f'Primeiro quartil (Q1): {q1_valor_venda_categoria}')
print(f'Segundo quartil (Q2, Mediana): {q2_valor_venda_categoria}')
print(f'Terceiro quartil (Q3): {q3_valor_venda_categoria}')

print(f'O valor da média é {media_valor_venda_categoria}')
print(f'O valor da mediana é {mediana_valor_venda_categoria}')
print(f'A distância entre média e mediana é de {distancia_valor_venda_categoria * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_valor_venda_categoria}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_valor_venda_categoria}')

Primeiro quartil (Q1): 2892560.74
Segundo quartil (Q2, Mediana): 14495598.61
Terceiro quartil (Q3): 78552157.79
O valor da média é 99119652.224
O valor da mediana é 14495598.61
A distância entre média e mediana é de 583.7913693030993
O limite superior para detecção de outliers é 192041553.365
O limite inferior para detecção de outliers é -110596834.83500002

In [526]:
outliers_valor_venda_categoria_limite_inferior = df_valor_venda_categoria.loc[df_valor_venda_categoria['Valor de Venda'] <= limite_inferior_valor_venda_categoria]
outliers_valor_venda_categoria_limite_inferior = outliers_valor_venda_categoria_limite_inferior.sort_values(by='Valor de Venda')
outliers_valor_venda_categoria_limite_inferior

Empty DataFrame
Columns: [Categoria Produto, Valor de Venda]
Index: []

In [527]:
outliers_valor_venda_categoria_limite_superior = df_valor_venda_categoria.loc[df_valor_venda_categoria['Valor de Venda'] >= limite_superior_valor_venda_categoria]
outliers_valor_venda_categoria_limite_superior = outliers_valor_venda_categoria_limite_superior.sort_values(by='Valor de Venda', ascending=False)
outliers_valor_venda_categoria_limite_superior

  Categoria Produto  Valor de Venda
1       Eletrônicos  398,284,376.66

Valor de venda por loja, produto, categoria e estado

In [528]:
df_valor_venda_loja_prod_estado_categ = df
df_valor_venda_loja_prod_estado_categ = df.groupby(
    ['Loja', 'Produto', 'Estado Loja', 'Categoria Produto']
)['Valor de Venda'].sum().reset_index()
df_valor_venda_loja_prod_estado_categ

,Loja,Produto,Estado Loja,Categoria Produto,Valor de Venda
0,Andrade,1984,SP,Livros,"13,403.58"
1,Andrade,A Culpa é das Estrelas,SP,Livros,"9,343.23"
2,Andrade,A Revolução dos Bichos,SP,Livros,"10,236.41"
3,Andrade,Arroz,SP,Alimentos,"19,781.09"
4,Andrade,Banco,SP,Móveis,"630,531.65"
...,...,...,...,...,...
1015,Vargas,TV,RJ,Eletrônicos,"961,518.28"
1016,Vargas,Tablet,RJ,Eletrônicos,"1,085,467.96"
1017,Vargas,Teclado,RJ,Eletrônicos,"1,993,144.79"
1018,Vargas,Tênis,RJ,Roupas,"71,734.53"
1019,Vargas,Vestido,RJ,Roupas,"58,116.16"

In [529]:
array_valor_venda_loja_prod_estado_categ = np.array(df_valor_venda_loja_prod_estado_categ['Valor de Venda'])

q1_valor_venda_loja_prod_estado_categ = np.percentile(array_valor_venda_loja_prod_estado_categ, 25)
q2_valor_venda_loja_prod_estado_categ = np.percentile(array_valor_venda_loja_prod_estado_categ, 50)
q3_valor_venda_loja_prod_estado_categ = np.percentile(array_valor_venda_loja_prod_estado_categ, 75)

media_valor_venda_loja_prod_estado_categ = np.mean(array_valor_venda_loja_prod_estado_categ)
mediana_valor_venda_loja_prod_estado_categ = np.median(array_valor_venda_loja_prod_estado_categ)
distancia_valor_venda_loja_prod_estado_categ = (media_valor_venda_loja_prod_estado_categ - mediana_valor_venda_loja_prod_estado_categ) / mediana_valor_venda_loja_prod_estado_categ

iqr_valor_venda_loja_prod_estado_categ = q3_valor_venda_loja_prod_estado_categ - q1_valor_venda_loja_prod_estado_categ
limite_superior_valor_venda_loja_prod_estado_categ = q3_valor_venda_loja_prod_estado_categ + (1.5 * iqr_valor_venda_loja_prod_estado_categ)
limite_inferior_valor_venda_loja_prod_estado_categ = q1_valor_venda_loja_prod_estado_categ - (1.5 * iqr_valor_venda_loja_prod_estado_categ)

print(f'Primeiro quartil (Q1): {q1_valor_venda_loja_prod_estado_categ}')
print(f'Segundo quartil (Q2, Mediana): {q2_valor_venda_loja_prod_estado_categ}')
print(f'Terceiro quartil (Q3): {q3_valor_venda_loja_prod_estado_categ}')

print(f'O valor da média é {media_valor_venda_loja_prod_estado_categ}')
print(f'O valor da mediana é {mediana_valor_venda_loja_prod_estado_categ}')
print(f'A distância entre média e mediana é de {distancia_valor_venda_loja_prod_estado_categ * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_valor_venda_loja_prod_estado_categ}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_valor_venda_loja_prod_estado_categ}')

Primeiro quartil (Q1): 10220.634999999998
Segundo quartil (Q2, Mediana): 57800.009999999995
Terceiro quartil (Q3): 617024.065
O valor da média é 485880.64815686276
O valor da mediana é 57800.009999999995
A distância entre média e mediana é de 740.6238133122516
O limite superior para detecção de outliers é 1527229.21
O limite inferior para detecção de outliers é -899984.5099999999

In [530]:
outliers_valor_venda_loja_prod_estado_categ_limite_inferior = df_valor_venda_loja_prod_estado_categ.loc[df_valor_venda_loja_prod_estado_categ['Valor de Venda'] <= limite_inferior_valor_venda_loja_prod_estado_categ]
outliers_valor_venda_loja_prod_estado_categ_limite_inferior = outliers_valor_venda_loja_prod_estado_categ_limite_inferior.sort_values(by='Valor de Venda')
outliers_valor_venda_loja_prod_estado_categ_limite_inferior

Empty DataFrame
Columns: [Loja, Produto, Estado Loja, Categoria Produto, Valor de Venda]
Index: []

In [531]:
outliers_valor_venda_loja_prod_estado_categ_limite_superior = df_valor_venda_loja_prod_estado_categ.loc[df_valor_venda_loja_prod_estado_categ['Valor de Venda'] >= limite_superior_valor_venda_loja_prod_estado_categ]
outliers_valor_venda_loja_prod_estado_categ_limite_superior = outliers_valor_venda_loja_prod_estado_categ_limite_superior.sort_values(by='Valor de Venda', ascending=False)
outliers_valor_venda_loja_prod_estado_categ_limite_superior

,Loja,Produto,Estado Loja,Categoria Produto,Valor de Venda
558,Mendonça Machado Ltda.,Teclado,SP,Eletrônicos,"8,233,232.01"
522,Mendonça Machado Ltda.,Celular,SP,Eletrônicos,"7,453,869.92"
530,Mendonça Machado Ltda.,Fone de Ouvido,SP,Eletrônicos,"7,015,342.43"
539,Mendonça Machado Ltda.,Monitor,SP,Eletrônicos,"5,502,977.88"
540,Mendonça Machado Ltda.,Mouse,SP,Eletrônicos,"5,053,154.29"
...,...,...,...,...,...
607,Moreira,TV,RJ,Eletrônicos,"1,556,251.34"
216,Cunha Gomes - EI,Celular,RS,Eletrônicos,"1,543,537.78"
864,Santos,Teclado,MG,Eletrônicos,"1,539,876.33"
507,Melo,Teclado,BA,Eletrônicos,"1,539,617.13"
683,Nunes,Fone de Ouvido,MG,Eletrônicos,"1,529,832.48"

Quantidade por Categoria de Produto

In [532]:
df_categoria_produto_quantidade = df
df_categoria_produto_quantidade = df.groupby(['Categoria Produto']).size().reset_index(name='Quantidade')
df_categoria_produto_quantidade = df_categoria_produto_quantidade.groupby(['Categoria Produto'])['Quantidade'].sum().reset_index().sort_values(by='Quantidade', ascending=True)
df_categoria_produto_quantidade

  Categoria Produto  Quantidade
2            Livros        7070
3            Móveis       14049
1       Eletrônicos       21475
4            Roupas       35808
0         Alimentos       71598

In [533]:
array_categoria_produto_quantidade = np.array(df_categoria_produto_quantidade['Quantidade'])

q1_categoria_produto_quantidade = np.percentile(array_categoria_produto_quantidade, 25)
q2_categoria_produto_quantidade = np.percentile(array_categoria_produto_quantidade, 50)
q3_categoria_produto_quantidade = np.percentile(array_categoria_produto_quantidade, 75)

media_categoria_produto_quantidade = np.mean(array_categoria_produto_quantidade)
mediana_categoria_produto_quantidade = np.median(array_categoria_produto_quantidade)
distancia_categoria_produto_quantidade = (media_categoria_produto_quantidade - mediana_categoria_produto_quantidade) / mediana_categoria_produto_quantidade

iqr_categoria_produto_quantidade = q3_categoria_produto_quantidade - q1_categoria_produto_quantidade
limite_superior_categoria_produto_quantidade = q3_categoria_produto_quantidade + (1.5 * iqr_categoria_produto_quantidade)
limite_inferior_categoria_produto_quantidade = q1_categoria_produto_quantidade - (1.5 * iqr_categoria_produto_quantidade)

print(f'Primeiro quartil (Q1): {q1_categoria_produto_quantidade}')
print(f'Segundo quartil (Q2, Mediana): {q2_categoria_produto_quantidade}')
print(f'Terceiro quartil (Q3): {q3_categoria_produto_quantidade}')

print(f'O valor da média é {media_categoria_produto_quantidade}')
print(f'O valor da mediana é {mediana_categoria_produto_quantidade}')
print(f'A distância entre média e mediana é de {distancia_categoria_produto_quantidade * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_categoria_produto_quantidade}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_categoria_produto_quantidade}')

Primeiro quartil (Q1): 14049.0
Segundo quartil (Q2, Mediana): 21475.0
Terceiro quartil (Q3): 35808.0
O valor da média é 30000.0
O valor da mediana é 21475.0
A distância entre média e mediana é de 39.69732246798603
O limite superior para detecção de outliers é 68446.5
O limite inferior para detecção de outliers é -18589.5

In [534]:
outliers_categoria_produto_quantidade_limite_inferior = df_categoria_produto_quantidade.loc[df_categoria_produto_quantidade['Quantidade'] <= limite_inferior_categoria_produto_quantidade]
outliers_categoria_produto_quantidade_limite_inferior = outliers_categoria_produto_quantidade_limite_inferior.sort_values(by='Quantidade')
outliers_categoria_produto_quantidade_limite_inferior

Empty DataFrame
Columns: [Categoria Produto, Quantidade]
Index: []

In [535]:
outliers_categoria_produto_quantidade_limite_superior = df_categoria_produto_quantidade.loc[df_categoria_produto_quantidade['Quantidade'] >= limite_superior_categoria_produto_quantidade]
outliers_categoria_produto_quantidade_limite_superior = outliers_categoria_produto_quantidade_limite_superior.sort_values(by='Quantidade', ascending=False)
outliers_categoria_produto_quantidade_limite_superior

  Categoria Produto  Quantidade
0         Alimentos       71598

In [540]:
df_loja_quantidade = df
df_loja_quantidade = df.groupby(['Loja']).size().reset_index(name='Quantidade')
df_loja_quantidade = df_loja_quantidade.groupby(['Loja'])['Quantidade'].sum().reset_index().sort_values(by='Quantidade', ascending=False)
df_loja_quantidade

                               Loja  Quantidade
1   Aparecida da Conceição e Filhos        7635
4                  Cunha Gomes - EI        7603
15              Sampaio Viana Ltda.        7579
9                              Melo        7578
3                             Cunha        7555
5                 Cunha Mendes S.A.        7542
2                           Barbosa        7518
0                           Andrade        7514
7                             Gomes        7499
14            Ribeiro Sampaio Ltda.        7485
13                            Nunes        7478
12                       Moura - ME        7464
6                         Fernandes        7463
19                           Vargas        7460
8                           Machado        7459
11                          Moreira        7453
17                            Sousa        7449
10           Mendonça Machado Ltda.        7432
16                           Santos        7432
18                         Teixeira        7402

In [537]:
array_loja_quantidade = np.array(df_loja_quantidade['Quantidade'])

q1_loja_quantidade = np.percentile(array_loja_quantidade, 25)
q2_loja_quantidade = np.percentile(array_loja_quantidade, 50)
q3_loja_quantidade = np.percentile(array_loja_quantidade, 75)

media_loja_quantidade = np.mean(array_loja_quantidade)
mediana_loja_quantidade = np.median(array_loja_quantidade)
distancia_loja_quantidade = (media_loja_quantidade - mediana_loja_quantidade) / mediana_loja_quantidade

iqr_loja_quantidade = q3_loja_quantidade - q1_loja_quantidade
limite_superior_loja_quantidade = q3_loja_quantidade + (1.5 * iqr_loja_quantidade)
limite_inferior_loja_quantidade = q1_loja_quantidade - (1.5 * iqr_loja_quantidade)

print(f'Primeiro quartil (Q1): {q1_loja_quantidade}')
print(f'Segundo quartil (Q2, Mediana): {q2_loja_quantidade}')
print(f'Terceiro quartil (Q3): {q3_loja_quantidade}')

print(f'O valor da média é {media_loja_quantidade}')
print(f'O valor da mediana é {mediana_loja_quantidade}')
print(f'A distância entre média e mediana é de {distancia_loja_quantidade * 100}')

print(f'O limite superior para detecção de outliers é {limite_superior_loja_quantidade}')
print(f'O limite inferior para detecção de outliers é {limite_inferior_loja_quantidade}')

Primeiro quartil (Q1): 7457.5
Segundo quartil (Q2, Mediana): 7481.5
Terceiro quartil (Q3): 7545.25
O valor da média é 7500.0
O valor da mediana é 7481.5
A distância entre média e mediana é de 0.24727661565194145
O limite superior para detecção de outliers é 7676.875
O limite inferior para detecção de outliers é 7325.875

In [538]:
outliers_loja_quantidade_limite_inferior = df_loja_quantidade.loc[df_loja_quantidade['Quantidade'] <= limite_inferior_loja_quantidade]
outliers_loja_quantidade_limite_inferior = outliers_loja_quantidade_limite_inferior.sort_values(by='Quantidade')
outliers_loja_quantidade_limite_inferior

Empty DataFrame
Columns: [Loja, Quantidade]
Index: []

In [539]:
outliers_loja_quantidade_limite_superior = df_loja_quantidade.loc[df_loja_quantidade['Quantidade'] >= limite_superior_loja_quantidade]
outliers_loja_quantidade_limite_superior = outliers_loja_quantidade_limite_superior.sort_values(by='Quantidade', ascending=False)
outliers_loja_quantidade_limite_superior

Empty DataFrame
Columns: [Loja, Quantidade]
Index: []